export interface DatosRegistro {
	nombres: string,
	primerapellido: string,
	segundoapellido: string,
	nacimiento_fecha: Date,
	nacimiento_entidad: string,
	nacimiento_lugar: string,
	sexo: string,
	curp: string,
	telefono: string,
	mail: string,
	codigovalidacion: string,
	validado: boolean,
	matricula: string,
	estatusformacion: number,
	fechainstitucion: Date,
	estatusministerio: number,
	fechadefusion: Date,
	id_user: number,
}